locale/pt_BR.po
Hi,
I just created a translation for the Portuguese (Brazilian) language.
=> add Portuguese (Brazilian) translation

Makefile
=> move bash-completion to the correct place

circle.yml, downgrade, test/helper.sh, test/sort_packages.t
=> Use pacsort to ensure proper package sorting

locale/es.po
Added a translation to spanish
=> Added translation to spanish

downgrade, test/main.t, test/search_arm.t, test/search_cache.t
This is accomplished by two features together:
1. Don't present packages if there's only one choice
1. Allow searches to include version
=> Allow downgrading to a specific version without prompting

doc/downgrade.8.md, downgrade, test/main/invalid-choice.t, test/main/no-candidates.t, test/main/one-choice.t, test/main/success.t, test/present_packages/installed.t
=> Denote previously-installed versions in output

downgrade
per issue 70 discussion:
https://github.com/pbrisbin/downgrade/issues/70
=> Add -maxdepth 1 to find command

downgrade, test/bin/column, test/extract_version/main.t, test/main/invalid-choice.t, test/main/success.t, test/present_packages/currently-installed.t, test/present_packages/installed.t, test/present_packages/success.t
Fixes #49.
[Sample output.txt](https://github.com/pbrisbin/downgrade/files/2980863/Sample.output.txt)
=> Organize package info into a table

doc/downgrade.8.md
=> Improve documentation

downgrade, locale/cs.po, locale/downgrade.pot, locale/es.po, locale/fr.po, locale/lt.po, locale/nb.po, locale/nn.po, locale/pl.po, locale/pt_BR.po, locale/ru.po, locale/zh_CN.po
Pull request to merge changes from #127 along with locale updates.
=> Ignore prompt default option clarification

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/questions_help.md, .github/PULL_REQUEST_TEMPLATE.md
1. This PR modifies bug templates to include clickable tick-boxes, because the previous ones were not.
2. Next, it also introduces a PR template with clickable tasks that should be completed for a PR to be merged. I find this to be a good practice for us to monitor the progress of each PR.
=> Modification of bug templates and additon of PR template

README.md, completion/fish, completion/zsh, doc/downgrade.8, doc/downgrade.8.md, downgrade, locale/cs.po, locale/downgrade.pot, locale/es.po, locale/fr.po, locale/lt.po, locale/nb.po, locale/nn.po, locale/pl.po, locale/pt_BR.po, locale/ru.po, locale/zh_CN.po, test/options_sanity/options_sanity.t
This PR addresses part of #138 by removing `--nosudo` related logic. ~Will hold merge until the other part of #138 is complete, ie. fixing the configuration file workflow.~
=> Goodbye --nosudo

CHANGELOG.md, README.md
Just some book-keeping stuff before release:
1. Updated the changelog assuming a minor bump, but I can change that if we agree to something else.
2. Modified the version filtering example in the readme to have single quotes instead of double, since the double ones might lead to undesired variable expansions.
=> Book-keeping before release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/questions_help.md, .github/PULL_REQUEST_TEMPLATE.md
Quick PR to update our GitHub templates for consistency and to reflect the new `--version` command-line option.
=> Update GitHub templates

downgrade
=> Bugfix for multiple architectures

downgrade, test/prompt_to_ignore/missing-option-present-header.t
This PR addresses #183 and adds a new test case
=> Bugfix for missing `IgnorePkg` directive

.github/PULL_REQUEST_TEMPLATE.md
Add a new check in PR template for updating configuration file in case we have new CLI arguments
**Edit:** Add categories for checklist
=> Update PR template checklist

CHANGELOG.md, downgrade, locale/cs.po, locale/downgrade.pot, locale/es.po, locale/fr.po, locale/lt.po, locale/nb.po, locale/nn.po, locale/pl.po, locale/pt_BR.po, locale/ru.po, locale/zh_CN.po
* Admin:
* Integration:
* Documentation:
* Release:
With the previous three bugfixes, I'd say we could release with a minor version bump.
=> Minor version bump to `v11.1.0`

CHANGELOG.md, bin/downgrade
* Release:
This PR proposes a minor version bump and release of `v11.2.0`. I will also update the URLs in our `PKGBUILD` to reflect this GitHub Org.
=> Release v11.2.0

completion/pacignore/zsh
* Admin:
* Integration:
* Documentation:
* Release:
=> Correct a typo in zsh completion

conf/downgrade.conf
And trim whitespace. Closes #218.
=> Clarify commented options as default-vs-example

.github/workflows/release.yml
Extracted `archlinux-downgrade/aur-publish-action` to handle things.
=> fix(release): automate PKGBUILD maintenance
