downgrade

it would be a great idea to also retrieve the remote signature
file of a package that is downloaded via pure unsecured http.
Without downloading the signature file it is very easy to use a
man-in-the-middle attack to deploy arbitrary files onto the victims
machine.
Maybe also consider creating a new release after this fix :smile:

checking remote package signatures to fix MitM vulnerability

---

downgrade
test/present_packages.t

These names are (effectively) basename of the URLs parsed out of the HTML index
and so are URL-encoded. Decoding them not only looks better but ensures things
sort correctly.

URL-decode remote package names

---

downgrade
test/search_cache.t

Default to ${PACMAN_CACHE:-/var/cache/pacman/pkg/}
Fixes #47

Handle missing CacheDir in pacman.conf

---

.codeclimate.yml
doc/downgrade.8
doc/downgrade.8.md

- Trim whitespace
- Don't specify "in the ALA" for values that also apply to local
- Avoid interpreting \*location\* as a header

Fixup manpage OUTPUT section

---

downgrade

This PR fixes `downgrade` for packages with the extension `.zst`, which is the new default package compression extension.
This PR also changes the package extension matching regex for ALA and CACHE resemble each other more.

Fix downgrade not finding packages with .zst extension

---

downgrade
test/extract_version/main.t
test/search_cache/config-missing.t
test/search_cache/pacman-conf-multiple.t
test/search_cache/pacman-conf-single.t
test/search_cache/specific-version.t
test/sort_packages/by-filename.t
test/sort_packages/omits-testing.t

This fixes #92.
The old behavior is preserved if a version-like string is passed in because there isn't a way to decide if there is a (partial) version or not.
There are still scenarios that downgrade doesn't work but people should find that downgrade works for strictly more package names without any new issues.

Use less restrictive package file patterns by fully matching the filename

---

CHANGELOG.md
README.md
doc/downgrade.8
doc/downgrade.8.md

Just realized there was a typo in the readme regarding the cache file path. Also, just added the `gitlocalize` badge to our readme, just so users could know that we offer multilingual scripts.
Would it be fine if I squash merged these to master?

Typo in man-page and readme update

---

.gitignore
CHANGELOG.md
Makefile
README.md
doc/downgrade.8
doc/downgrade.8.md
downgrade
locale/cs.po
locale/downgrade.pot
locale/es.po
locale/fr.po
locale/lt.po
locale/nb.po
locale/nn.po
locale/pl.po
locale/pt_BR.po
locale/ru.po
locale/zh_CN.po

**NOTE**: there are number of minor but distinct commits here, which I've pulled
from #114. Please consider reviewing this PR by paging through the Commits tab
one-by-one.
The important commits here are:
- 539160f Find TEXTDOMAINDIR relative to script
Previously, downgrade hard-coded `/usr/share/locale`. This meant
installation to an alternative `PREFIX` would still use `/usr` for the
locale files, which is surprising.
This change means that wherever downgrade is installed, it will find locales
relative to itself. This is behavior neutral on Arch, since the PKGBUILD[1]
uses an explicit `PREFIX` of `/usr`.
A future commit will bring the locale files installation into the make install
target, which will respect PREFIX. That will only function with the
pre-requisite commit.
[1]: …

Respect PREFIX in locale files' installation

---

README.md
completion/zsh
doc/downgrade.8.md
downgrade
locale/cs.po
locale/downgrade.pot
locale/es.po
locale/fr.po
locale/lt.po
locale/nb.po
locale/nn.po
locale/pl.po
locale/pt_BR.po
locale/ru.po
locale/zh_CN.po
test/options_sanity/options_sanity.t

This PR addresses #120 by adding `--pacman-cache`, `--pacman-log` and `--maxdepth` as CLI options. Commits have been chunked to represent discrete components of this PR.
Regarding whether to include `--maxdepth` at all, I think it is a good idea to include this parameter to ensure that `find` does not get stuck searching some deep user-defined cache directory. The user can add an arbitrarily large value for this if they want to search some basic cache directory for (eg.) AUR packages.

Add --pacman-cache, --pacman-log and --maxdepth to CLI options

---

downgrade
locale/cs.po
locale/downgrade.pot
locale/es.po
locale/fr.po
locale/lt.po
locale/nb.po
locale/nn.po
locale/pl.po
locale/pt_BR.po
locale/ru.po
locale/zh_CN.po
test/options_sanity/unrecognized_option.t

With the increasing number of command-line options (given proposals in #118), I thought it would be a good idea to introduce another error handling procedure during parsing options in case an option is not recognized (perhaps was spelt wrongly).
The current behaviour would just add an unrecognized option as a package to downgrade; and maybe this could be considered annoying.
This PR catches any option starting with a `-` that is not captured as `--` or by any of the existing command-line options. I checked the arch package repositories and could not find any package starting with a `-`, so I think this is a safe assumption to catch an unrecognized option.
I updated the tests to check for this. I also updated the locales to include a new key.

Error handling for unrecognized command-line options

---

downgrade

This PR addresses #119 where `downgrade` does not follow symlink(s) to another cache directory. This is because of the default behaviour of `find`. To address this, we can add the `-L` flag to `find`, such that it will traverse all symlinks to find relevant cached tarballs. Despite some reservations, this is still made secure because of the `--maxdepth` option which would prevent problematic recursions.
PS: I left out the locale update for when we release. I think we can release this and the previous commits for unrecognized options as a minor version bump.

Adding -L flag to find to search explicitly provided symlinks

---

CHANGELOG.md

PR for patch version bump to `v8.1.1`, address #131. After the merge, will create the tag via GitHub UI (should be possible) and then update the AUR.

Release v8.1.1

---

README.md
completion/zsh
doc/downgrade.8
doc/downgrade.8.md
downgrade
locale/cs.po
locale/downgrade.pot
locale/es.po
locale/fr.po
locale/lt.po
locale/nb.po
locale/nn.po
locale/pl.po
locale/pt_BR.po
locale/ru.po
locale/zh_CN.po
test/options_sanity/options_sanity.t

~- [ ] **Optional:** This might be an extreme edge case. Assume if the same package is present in two different pacman cache locations (maybe because it was an AUR package before and got shifted to one of the official repos later on). Based on local tests, I noticed that `downgrade` now would display the package twice in the menu. This could be solved by showing the location of the cache corresponding to the package in the menu, but I can imagine the menu would look horrible. Another option would be to just show one (unique) package if multiple copies are present. WDYT?~
This PR addresses #135 by modfying the `PACMAN_CACHE` variable read from stdin into a bash array. This allows us to search multiple cache locations with the `search_packages` function. Based on local tests, it also does …

Pacman cache accumulation

---

Makefile
README.md
completion/fish
completion/zsh
doc/downgrade.8
doc/downgrade.8.md
downgrade
locale/cs.po
locale/downgrade.pot
locale/es.po
locale/fr.po
locale/lt.po
locale/nb.po
locale/nn.po
locale/pl.po
locale/pt_BR.po
locale/ru.po
locale/zh_CN.po

This PR addresses #147 by proposing a new `--version` command-line option. This prints out the `DOWNGRADE_VERSION` variable that is defined internally.
I chose to forego the whole process with `m4` as it seemed bulky compared to the simple regular-expression based replacement that is required for this. Also I am sure we will never define the `DOWNGRADE_VERSION` variable in any other context in `downgrade`, so the absolute replacement using `sed` should be safe.
WDYT?

Add --version command-line option

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
downgrade

Changes are as follows:
1. Remove feature in `Makefile` which updates `DOWNGRADE_VERSION` automatically, since this results in branch protection problems
2. Add the task of updating `DOWNGRADE_VERSION` manually to GitHub PR templates
3. Update `DOWNGRADE_VERSION` to `v10.1.0` for this minor version bump and release

Release v10.1.0

---

test/main/term_operator_version_parsing.t

A test for the `=~` operator was missing, so just updating it with this PR.

Patch test in `term_operator_version_parsing.t`

---

CHANGELOG.md
README.md
doc/downgrade.8
doc/downgrade.8.md

* Admin:
* Integration:
* Documentation:
* Release:
This PR migrates existing GitHub URLs to `archlinux-downgrade`. A redirect from the old URL already exists, but just thought it would be prudent to do it anyways.
As a reminder (to myself), I would also have to update the source URL in the `PKGBUILD` before our next release.

Migrate GitHub URLs to `archlinux-downgrade`

---

.github/ISSUE_TEMPLATE/questions_help.md

Replace `needs triage` label to `triage`
* Admin:
* Integration:
* Documentation:
* Release:
Fix label from `needs triage` to `triage`

Fix bug in issue template for question

---

bin/pacignore
test/pacignore/add_failure.t
test/pacignore/add_success.t
test/pacignore/check_failure.t
test/pacignore/check_success.t
test/pacignore/ls_failure.t
test/pacignore/ls_success.t
test/pacignore/parse_failure.t
test/pacignore/parse_success.t
test/pacignore/rm_failure.t
test/pacignore/rm_success.t

* Admin:
* Integration:
This PR proposes the following changes:
1. As discussed earlier, use POSIX `getopts` for pasing CLI options in lower-level scripts; specifically `pacignore` here
2. Update tests to use shorter CLI options and to test error messages as well

Use POSIX `getopts` in `pacignore`

---

bin/downgrade
test/helper.sh
test/prompt_to_ignore/already-present.t
test/prompt_to_ignore/commented-multiple.t
test/prompt_to_ignore/commented-whitespace.t
test/prompt_to_ignore/commented.t
test/prompt_to_ignore/missing-option-present-header.t
test/prompt_to_ignore/missing-option.t
test/prompt_to_ignore/multiple-arguments.t
test/prompt_to_ignore/multiple-uncommented.t
test/prompt_to_ignore/no-arguments.t
test/prompt_to_ignore/user-approves.t
test/prompt_to_ignore/whitespace.t

* Admin:
* Integration:
To work towards smaller and more compact PRs, I moved (and split) a commit from the `as/pacignore` branch to this branch. This PR proposes the following:
1. Use `pacignore` directly in `downgrade` as a form of integration
2. Simplify unit tests of `downgrade` to no longer test features of what is now `pacignore`. Instead, we only test integration between the two scripts.

Integrate `pacignore` into `downgrade`

---

CHANGELOG.md
Makefile
bin/downgrade

* Admin:
* Release:
This PR addresses #205 by renaming internal variables in `Makefile` to reduce the chances of variable-name conflicts

Patch Makefile to avoid variable-name conflicts

---

completion/downgrade/zsh
completion/pacignore/zsh

* Admin:
* Integration:
Following #211, I thought it would be a good idea to implement ZSH completion caching for `pacignore` (as we have it now for `downgrade`). This PR does the following:
1. 88fa098887f04514ede7d979f56f306cdcc36d19: Implements the ZSH completion caching feature for `pacignore`
2. f13c35772fcf3dee208394ffb314a51197fa7135: Potentially fixes a bug in the caching for both `downgrade` and `pacignore` by checking if `pacman.log` is newer than the cache, instead of vice versa that was done before
@pbrisbin could you help me check if the fix in point (2) makes sense? I could not find much documentation on the ZSH completion caching policy...

Patch ZSH completions

---

bin/downgrade
test/present_packages/currently-installed.t
test/present_packages/installed.t
test/present_packages/success.t

Include last-modified for cached packages
